# Generated by Django 4.1 on 2022-08-13 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_location', models.TextField(max_length=400)),
                ('end_location', models.TextField(max_length=400)),
                ('distance', models.IntegerField()),
                ('days_per_week_commuting', models.IntegerField()),
                ('start_avg_gas', models.IntegerField(null=True)),
                ('end_avg_gas', models.IntegerField(null=True)),
                ('avg_gas_commute', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('make', models.IntegerField(null=True)),
                ('model', models.IntegerField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('mpg', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('daily', models.IntegerField(null=True)),
                ('weekly', models.IntegerField(null=True)),
                ('monthly', models.IntegerField(null=True)),
                ('annual', models.IntegerField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('title', models.TextField(max_length=400)),
                ('commute', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='commutilator_api.commute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='commutilator_api.vehicle')),
            ],
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.UniqueConstraint(fields=('vehicle', 'commute'), name='unique_result'),
        ),
    ]
