# Generated by Django 4.0 on 2022-08-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commutilator_api', '0002_alter_commute_end_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commute',
            name='avg_gas_commute',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='commute',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='commute',
            name='end_avg_gas',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='commute',
            name='start_avg_gas',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='annual',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='daily',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='monthly',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='weekly',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='mpg',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
    ]
