# Generated by Django 4.0 on 2022-08-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commutilator_api', '0003_alter_commute_avg_gas_commute_alter_commute_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='mpg',
            field=models.IntegerField(null=True),
        ),
    ]
