# Generated by Django 4.1 on 2022-08-16 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commutilator_api', '0007_calculationdata_remove_result_unique_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculationdata',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to=settings.AUTH_USER_MODEL),
        ),
    ]
