# Generated by Django 4.1 on 2022-08-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commutilator_api', '0008_alter_calculationdata_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(check=models.Q(('mpg__isnull', False), ('model__isnull', False), _connector='OR'), name='not_both_null'),
        ),
    ]
