# Generated by Django 4.1 on 2022-08-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commutilator_api', '0009_vehicle_not_both_null'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vehicle',
            name='not_both_null',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='mpg',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
