# Generated by Django 4.0 on 2022-08-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commutilator_api', '0014_alter_calculationdata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='commute',
            name='directions_response',
            field=models.TextField(null=True),
        ),
    ]
