# Generated by Django 4.0 on 2022-08-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commutilator_api', '0015_commute_directions_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commute',
            name='directions_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
